packages:
  - 'apps/*'
  - 'packages/*'
  - 'services/*'
allowBuilds:
  'esbuild': true
  '@nestjs/core': true
  '@shopify/react-native-skia': true
  sqlite3: true
  msgpackr-extract: true
  protobufjs: true
